### ISSUE TITLE
summarization-api-playground shows an error until you manually call `await ai.summarizer.create();`

### ISSUE THREAD

**Issue by michaelwasserman** [GoogleChromeLabs/web-ai-demos#81] opened 2024-11-15 22:28 UTC
My Chrome is setup correctly (AFAICT) and prompt API WAI, but I got an error on my first summarization use:
"The Summarization API is available, but your device is unable to run it."
I had to open devtools and run `await ai.summarizer.create();` (and then reload?) to make the demo work.
New profiles seem to WAI, but it might repro with a new user-data-dir + re-setup?

**Comment by michaelwasserman** [comment] 2024-11-15 22:28
FYI: @tomayac

**Comment by tomayac** [comment] 2024-11-18 08:33
There were some hiccups with the API temporarily entering a bad state (that were reported as Chromium bugs), but I don't think there's anything actionable on our end. The way @andreban initializes the session is perfectly by the book:
https://github.com/GoogleChromeLabs/web-ai-demos/blob/d10bcae3e2b0c74399593c80e28d0b90370ddb0f/summarization-api-playground/src/main.ts#L34-L53 

@andreban, you encountered this issue, too, where you needed to force the session to start by multiple `create()` calls. As I said, I don't think there's anything actionable here, though.

**Comment by andreban** [comment] 2024-11-18 09:24
There's a bug filed for this at https://issues.chromium.org/issues/379074334.

> @andreban, you encountered this issue, too, where you needed to force the session to start by multiple create() calls. As I said, I don't think there's anything actionable here, though.

This was during the early access, caused by an issue where reusing the same summarizer would create instances, so a new one had to be created for each use. This has since been fixed.

**Comment by tomayac** [comment] 2024-11-18 09:31
Alright. We can close this issue then. Thanks for the report nonetheless, @michaelwasserman!

**Closed by tomayac** 2024-11-18 09:31 UTC

**Comment by andreban** [comment] 2024-11-19 14:20
This PR implements a workaround while the underlying bug is not fixed https://github.com/GoogleChromeLabs/web-ai-demos/pull/82/
